data:
  data_path: '/mnt/ssd_4tb_0/data/tuhab_preprocessed_normal_10_val_scalograms'
  batch_size: 128
  num_workers: 8
  prefetch_factor: 4
  pin_memory: True
  drop_last: True

model:
  image_size: (250, 1000)
  patch_size: (25, 100)
  num_classes: 1000
  dim: 1024
  depth: 6
  heads: 8
  mlp_dim: 2048
  pool: 'cls'
  channels: 1

  masking_ratio: 0.75
  decoder_dim: 512
  decoder_depth: 6

  revin: False

  save_path: 'saved_models/pretrain/scalogram_vit'
  checkpoint_interval: 0.1 # num_epochs or percentage

train:
  num_epochs: 10
  learning_rate: 1e-4
  weight_decay: 0
  scheduler: 'cosine'
  step_size: 10
  gamma: 0.1
  val_interval_epochs: 1

neptune:
  enabled: True
  project: 'gayalkuruppu/tuh-ssl-test'
  experiment_name: '10_val_normal_dataset'
