data:
  data_path: '/mnt/ssd_4tb_0/data/tuhab_preprocessed_normal_10_val_scalograms_5_sec'
  batch_size: 8
  num_workers: 8
  prefetch_factor: 4
  pin_memory: True
  drop_last: True

model:
  image_size: (70, 500)
  patch_size: (7, 10)
  num_classes: 1000
  dim: 1024 #d_model
  depth: 6
  heads: 8
  mlp_dim: 2048 # d_ff
  pool: 'cls'
  channels: 1

  head_type: 'pretrain'
  mask_type: 'random'
  time_masking_ratio: 0.2
  freq_masking_ratio: 0.2 # 0.36
  decoder_dim: 512
  decoder_depth: 6

  revin: False

  save_path: 'saved_models/pretrain/scalogram_vit'
  checkpoint_interval: 0.1 # num_epochs or percentage

train:
  num_epochs: 100
  learning_rate: 1e-3
  weight_decay: 0
  scheduler: 'cosine'
  step_size: 10
  gamma: 0.1
  val_interval_epochs: 10

  # masking
  time_mask_consecutive_min: 1
  time_mask_consecutive_max: 20
  freq_mask_consecutive_min: 1
  freq_mask_consecutive_max: 4
  time_mask_p: 0.10
  freq_mask_p: 0.10

neptune:
  enabled: True
  project: 'gayalkuruppu/tuh-ssl-test'
  experiment_name: '10_val_normal_dataset_spectrogram_5_sec'
