data:
  root_path: '/mnt/ssd_4tb_0/data/tuhab_preprocessed'
  data_path: ''
  csv_path: '/mnt/ssd_4tb_0/data/tuhab_preprocessed/file_lengths_map.csv'
  batch_size: 2
  num_workers: 8
  prefetch_factor: 4
  pin_memory: True
  drop_last: True
  n_vars: 19

model:
  seq_len: 1000
  target_dim: 0
  patch_length: 1
  stride: 1
  num_layers: 3
  d_model: 128
  num_heads: 16
  shared_embedding: True
  d_ff: 256
  norm: 'BatchNorm'
  attn_dropout: 0.0
  dropout: 0.2
  activation: 'relu'
  res_attention: True
  pe: 'sincos'
  learn_pe: True
  head_dropout: 0.2
  head_type: 'pretrain'
  use_cls_token: True
  
  revin: False
  revin_eps: 1e-5
  revin_affine: False # denorm False

  mask_ratio: 0.3
  masked_value: 0.0
  independent_channel_masking: True
  forecasting_num_patches: 300

  val_mask_types:
    - 'random'
    - 'forecasting'

  save_path: 'saved_models/pretrain'
  checkpoint_interval: 0.2 # num_epochs or percentage

train:
  num_epochs: 5
  learning_rate: 1e-4
  weight_decay: 0
  scheduler: 'cosine'
  val_interval_epochs: 1

neptune:
  enabled: True
  project: 'gayalkuruppu/tuh-ssl-test'
  experiment_name: 'tuhab_pretrain_patch_len_1'
