data:
  root_path: '/mnt/ssd_4tb_0/data/tuhab_preprocessed_normal_10_val'
  data_path: ''
  csv_path: '/mnt/ssd_4tb_0/data/tuhab_preprocessed_normal_10_val/file_lengths_map.csv'
  metadata_csv_path: '/mnt/ssd_4tb_0/data/tuhab_patient_metadata_ds.csv'
  metadata_dict_path: '/home/gayal/ssl-project/gpatchTST/preprocessing/outputs/alpha_power_tuab_normal_dict.pkl'
  batch_size: 64
  num_workers: 8
  dl_seed: 0
  prefetch_factor: 4
  pin_memory: True
  drop_last: False
  n_vars: 1
  dataloader: 'tuab_alpha_powers'

model:
  seq_len: 1000
  target_dim: 1
  patch_length: 100
  stride: 100
  num_layers: 3
  d_model: 128
  num_heads: 16
  shared_embedding: True
  d_ff: 256
  norm: 'BatchNorm'
  attn_dropout: 0.0
  dropout: 0.2
  activation: 'relu'
  res_attention: True
  pe: 'sincos'
  learn_pe: True
  head_dropout: 0.2
  head_type: 'regression'
  use_cls_token: True
  mode: 'linearprobe'
  o1_only: False
  
  revin: False
  revin_eps: 1e-5
  revin_affine: False # denorm False

  mask_ratio: 0.3
  masked_value: 0.0
  independent_channel_masking: True
  forecasting_num_patches: 3

  save_path: 'saved_models/supervised_learning'
  checkpoint_interval: 0.05 # num_epochs or percentage

train:
  num_epochs: 20
  learning_rate: 1e-2
  weight_decay: 0
  scheduler: 'cosine'
  val_interval_epochs: 1

neptune:
  enabled: True
  project: 'gayalkuruppu/ssl-eval'
  experiment_name: 'tuab_normal_10_val_linear_probe_patch_100'
